site_name: mini-Internet
pages:
    - mini-Internet: index.md
    - Introducción: intro.md
    - Instalación Ubuntu Server: ubuntu_server.md
    - IP Estática: ip_estatica.md
    - DNS: dns.md
    - extra: extra.md
    - Acerca de: about.md

theme: readthedocs